version: '3'
services:
  web:
    build: .
    container_name: consumer
    volumes:
    - .:/opt/app
    ports:
      - 4000:4000
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    networks:
      - freelancer-now
      - db-freelancer
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - freelancer_now_data:/var/lib/postgresql/data
    networks:
      - db-freelancer
volumes:
  freelancer_now_data:

networks: 
  freelancer-now: 
    external: true
  db-freelancer:
    external: false
